---
- hosts: localhost
  connection: local

  vars_files:
  - vars/env_vars.yml

  vars:
    avi_credentials:
      api_version: "{{ api_version }}"
      username: "{{ username }}"
      password: "{{ password }}"
      controller: "{{ cluster_leader_ip_site_a }}"

  roles:
    - avinetworks.avisdk

  tasks:

    - name: Wait for Controller be ready
      uri:
        validate_certs: False
        url: "http://{{ cluster_leader_ip_site_a }}/"
        method: GET
        status_code: 200,302,301,503
      register: statusCode_output
      until: statusCode_output.status == 200
      retries: 120
      delay: 60

    - name: Configuring Application Profile http
      avi_applicationprofile:
        avi_credentials: "{{ avi_credentials }}"
        name: "{{ item.app_profile_http_name }}"
        type: APPLICATION_PROFILE_TYPE_HTTP
        http_profile:
          max_rps_uri: 0
          fwd_close_hdr_for_bound_connections: true
          keepalive_header: false
          max_rps_cip_uri: 0
          x_forwarded_proto_enabled: false
          connection_multiplexing_enabled: "{{ connection_multiplexing_state  | default('true')}}"
          websockets_enabled: "{{ websockets_state | default('true')}}"
          enable_request_body_metrics: false
          http2_enabled: "{{ http2_state | default('false')}}"
          enable_request_body_buffering: false
          hsts_enabled: "{{ hsts_state | default('false')}}"
          hsts_subdomains_enabled: "{{ hsts_include_subdomains | default('true')}}"
          xff_enabled: "{{ xff_enabled_state | default('true')}}"
          hsts_max_age: "{{ hsts_max_age | default('365')}}"
          keepalive_timeout: 30000
          ssl_client_certificate_mode: SSL_CLIENT_CERTIFICATE_NONE
          http_to_https: "{{ http_to_https_state | default('false')}}"
          spdy_enabled: false
          respond_with_100_continue: true
          client_body_timeout: 30000
          httponly_enabled: "{{ httponly_state | default('false')}}"
          disable_keepalive_posts_msie6: true
          max_bad_rps_cip: 0
          server_side_redirect_to_https: "{{ server_side_redirect_to_https_state| default('false')}}"
          client_max_header_size: 12
          ssl_everywhere_enabled: "{{ ssl_everywhere_state | default('false')}}"
          max_rps_unknown_uri: 0
          client_max_request_size: 48
          spdy_fwd_proxy_mode: false
          allow_dots_in_header_name: false
          client_header_timeout: 10000
          post_accept_timeout: 30000
          secure_cookie_enabled: "{{ secure_cookie_state | default('false')}}"
          max_response_headers_size: 48
          xff_alternate_name: "{{ xff_alternate_name | default('X-Forwarded-For')}}"
          max_rps_cip: 0
          client_max_body_size: 0
          enable_fire_and_forget: false
          max_rps_unknown_cip: 0
          max_bad_rps_cip_uri: 0
          max_bad_rps_uri: 0
          use_app_keepalive_timeout: false
          preserve_client_port: false
          preserve_client_ip: "{{ preserve_client_ip_state | default('false')}}"
          dos_rl_profile:
            rl_profile:
              client_ip_connections_rate_limit:
                count: 0
                explicit_tracking: false
                period: 1
                action:
                  status_code: HTTP_LOCAL_RESPONSE_STATUS_CODE_429
                  type: RL_ACTION_NONE
                burst_sz: 0
                fine_grain: false
            dos_profile:
              thresh_period: 5
      with_item: "{{ app_profile }}"        
          
        
